// ISO 3166-1 alpha-3 country codes with names + flag emojis.
// Used by the countries-visited picker and world map highlighting.

export type Country = { code: string; name: string; flag: string };

export const COUNTRIES: Country[] = [
  { code: "USA", name: "United States", flag: "🇺🇸" },
  { code: "CAN", name: "Canada", flag: "🇨🇦" },
  { code: "MEX", name: "Mexico", flag: "🇲🇽" },
  { code: "GBR", name: "United Kingdom", flag: "🇬🇧" },
  { code: "IRL", name: "Ireland", flag: "🇮🇪" },
  { code: "FRA", name: "France", flag: "🇫🇷" },
  { code: "ESP", name: "Spain", flag: "🇪🇸" },
  { code: "PRT", name: "Portugal", flag: "🇵🇹" },
  { code: "ITA", name: "Italy", flag: "🇮🇹" },
  { code: "DEU", name: "Germany", flag: "🇩🇪" },
  { code: "NLD", name: "Netherlands", flag: "🇳🇱" },
  { code: "BEL", name: "Belgium", flag: "🇧🇪" },
  { code: "CHE", name: "Switzerland", flag: "🇨🇭" },
  { code: "AUT", name: "Austria", flag: "🇦🇹" },
  { code: "DNK", name: "Denmark", flag: "🇩🇰" },
  { code: "SWE", name: "Sweden", flag: "🇸🇪" },
  { code: "NOR", name: "Norway", flag: "🇳🇴" },
  { code: "FIN", name: "Finland", flag: "🇫🇮" },
  { code: "ISL", name: "Iceland", flag: "🇮🇸" },
  { code: "POL", name: "Poland", flag: "🇵🇱" },
  { code: "CZE", name: "Czechia", flag: "🇨🇿" },
  { code: "HUN", name: "Hungary", flag: "🇭🇺" },
  { code: "GRC", name: "Greece", flag: "🇬🇷" },
  { code: "TUR", name: "Turkey", flag: "🇹🇷" },
  { code: "RUS", name: "Russia", flag: "🇷🇺" },
  { code: "EGY", name: "Egypt", flag: "🇪🇬" },
  { code: "MAR", name: "Morocco", flag: "🇲🇦" },
  { code: "ZAF", name: "South Africa", flag: "🇿🇦" },
  { code: "KEN", name: "Kenya", flag: "🇰🇪" },
  { code: "TZA", name: "Tanzania", flag: "🇹🇿" },
  { code: "NGA", name: "Nigeria", flag: "🇳🇬" },
  { code: "ARE", name: "United Arab Emirates", flag: "🇦🇪" },
  { code: "SAU", name: "Saudi Arabia", flag: "🇸🇦" },
  { code: "ISR", name: "Israel", flag: "🇮🇱" },
  { code: "JOR", name: "Jordan", flag: "🇯🇴" },
  { code: "IND", name: "India", flag: "🇮🇳" },
  { code: "CHN", name: "China", flag: "🇨🇳" },
  { code: "JPN", name: "Japan", flag: "🇯🇵" },
  { code: "KOR", name: "South Korea", flag: "🇰🇷" },
  { code: "TWN", name: "Taiwan", flag: "🇹🇼" },
  { code: "HKG", name: "Hong Kong", flag: "🇭🇰" },
  { code: "SGP", name: "Singapore", flag: "🇸🇬" },
  { code: "THA", name: "Thailand", flag: "🇹🇭" },
  { code: "VNM", name: "Vietnam", flag: "🇻🇳" },
  { code: "PHL", name: "Philippines", flag: "🇵🇭" },
  { code: "IDN", name: "Indonesia", flag: "🇮🇩" },
  { code: "MYS", name: "Malaysia", flag: "🇲🇾" },
  { code: "AUS", name: "Australia", flag: "🇦🇺" },
  { code: "NZL", name: "New Zealand", flag: "🇳🇿" },
  { code: "BRA", name: "Brazil", flag: "🇧🇷" },
  { code: "ARG", name: "Argentina", flag: "🇦🇷" },
  { code: "CHL", name: "Chile", flag: "🇨🇱" },
  { code: "PER", name: "Peru", flag: "🇵🇪" },
  { code: "COL", name: "Colombia", flag: "🇨🇴" },
  { code: "ECU", name: "Ecuador", flag: "🇪🇨" },
  { code: "CRI", name: "Costa Rica", flag: "🇨🇷" },
  { code: "PAN", name: "Panama", flag: "🇵🇦" },
  { code: "GTM", name: "Guatemala", flag: "🇬🇹" },
  { code: "CUB", name: "Cuba", flag: "🇨🇺" },
  { code: "JAM", name: "Jamaica", flag: "🇯🇲" },
  { code: "DOM", name: "Dominican Republic", flag: "🇩🇴" },
];

export const COUNTRY_BY_CODE: Record<string, Country> = Object.fromEntries(
  COUNTRIES.map((c) => [c.code, c])
);
